### ISSUE TITLE
maven.config, dependencyManagement, and systemPath causes flatten goal to fail

### ISSUE THREAD

**Issue by rpatrick00** [mojohaus/flatten-maven-plugin#12] opened 2015-10-21 21:35 UTC
I have relatively complex Maven project where in my acceptance tests, I need to specify a dependency with a scope of system to point to an older version of some software that does not supply a Maven POM.  As such, I am using the Maven 3.3 capability to define a .mvn/maven.config file where my team (and my Hudson jobs) specify the path to the software installation in their environment.  Unfortunately, the flatten plugin is choking on this with the following error:

[ERROR] Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.0.0-beta-5:flatten (flatten) on project apps: 1 problem was encountered while building the effective model for test:apps:1.0
[ERROR] [ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.oracle.weblogic:weblogic-jar:jar must specify an absolute path but is ${path-to-wls1036}/server/lib/weblogic.jar @

The variable path-to-wls1036 is defined in the .mvn/maven.config file as follows:

-Dpath-to-wls1036=c:\wls1036\wlserver_10.3

If I comment out the flatten plugin, the build is successful.  I have a simple test case that demonstrates the problem.  Happy to send it in email since github does not allow me to attach the file to the issue...

**Comment by rpatrick00** [comment] 2015-10-21 21:48
The project structure to replicate this is as follows:

Top-Level, multi-module POM has a dependencyManagement section and a build section with a pluginManagement and plugins section.  The flatten plugin execution is configured in the plugins section of this POM.  This POM has an apps module.

The apps module POM is a multi-module POM that also has a dependencyManagement with the system-scoped dependency whose systemPath element is set to ${path-to-wls1036}/server/lib/weblogic.jar.  The POM has a get-listen-port-app module

The get-listen-port-app module POM builds a WAR file and declares a dependency on the system-scoped dependency like so:

    <dependencies>
        <dependency>
            <groupId>com.oracle.weblogic</groupId>
            <artifactId>weblogic-jar</artifactId>
        </dependency>
    </dependencies>

**Comment by hohwille** [comment] 2015-11-27 07:59
Also have a look at this PR that is slightly related:
https://github.com/mojohaus/flatten-maven-plugin/pull/13

**Comment by hohwille** [comment] 2015-11-27 08:02
Do I understand correctly that the problem seems to be a system scoped dependency that itself is using a variable/property in system path?
Are you aware that system dependencies are heavily discouraged and their support will be dropped in future maven versions (4.x)?
However, we do not have to do evangelism in flatten-maven-plugin. We can do ShI-ShO :)
So first we should create a minimal integration test here that can reproduce the bug:
https://github.com/mojohaus/flatten-maven-plugin/tree/master/src/it/projects

Then I can fix it.

**Comment by rpatrick00** [comment] 2015-11-28 00:37
Yes, I understand.  However, back in the real world of software development, sometimes things are not as clean as one would like them to be.  Here is another real-world example of something that is perfectly legal in Maven but that the flatten plugin is failing on:
<pre>
    &lt;dependencies&gt;
      &lt;dependency&gt;
	&lt;groupId&gt;com.oracle.java&lt;/groupId&gt;
	&lt;artifactId&gt;tools&lt;/artifactId&gt;
	&lt;version&gt;8.0&lt;/version&gt;
	&lt;scope&gt;system&lt;/scope&gt;
	&lt;systemPath&gt;${java.home}/../lib/tools.jar&lt;/systemPath&gt;
      &lt;/dependency&gt;
    &lt;/dependencies&gt;
</pre>

I have created a trivial little test case for you (my real situation is more complex).  I will create a pull request to add this test but note that the test fails unless I comment-out the flatten plugin execution.  I will comment it out in the pull request so that it doesn't break anything.  You will need to remove the comments to see the problem.

**Comment by hohwille** [comment] 2015-11-28 01:32
Your IT does not reproduce the bug. See our travis logs. I am tented to close this as invalid. Any further insights?
I also want to point out that in this example ${java.home} will be resolved in the flattened POM what is IMHO not intended. However, system scoped dependencies are no good idea anyway...
Maybe however I should think about making an exclusion for resolving ${java.home} and ${java.version} as these Properties are always available and should typically not be resolved in flattened POM...

**Comment by hohwille** [comment] 2015-11-28 01:33
I got it after reading once again. Your bug is actually a duplicate of #3 that I already fixed.

**Closed by hohwille** 2015-11-28 01:33 UTC
Labels: bug

**Comment by rpatrick00** [comment] 2015-11-28 02:07
H:\projects\forked\flatten-maven-plugin\src\it\projects\system-scope-dep-variabl
e>java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

H:\projects\forked\flatten-maven-plugin\src\it\projects\system-scope-dep-variabl
e>mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T06:57:3
7-05:00)
Maven home: c:\java\apache-maven-3.3.3
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: c:\java\jdk1.8.0\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

H:\projects\forked\flatten-maven-plugin\src\it\projects\system-scope-dep-variabl
e>mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building system-scope-dep-variable 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ system-sco
pe-dep-variable ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory H:\projects\forked\flatten-maven-plug
in\src\it\projects\system-scope-dep-variable\src\main\resources
[INFO]
[INFO] --- flatten-maven-plugin:1.0.0-beta-5:flatten (flatten) @ system-scope-de
p-variable ---
[INFO] Generating flattened POM of project org.codehaus.mojo.flatten.its:system-
scope-dep-variable:jar:0.1-SNAPSHOT...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.776 s
[INFO] Finished at: 2015-11-27T20:06:14-06:00
[INFO] Final Memory: 17M/491M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.0.0-beta
-5:flatten (flatten) on project system-scope-dep-variable: 1 problem was encount
ered while building the effective model for org.codehaus.mojo.flatten.its:system
-scope-dep-variable:0.1-SNAPSHOT
[ERROR] [ERROR] 'dependencies.dependency.systemPath' for com.oracle.java:tools:j
ar must specify an absolute path but is ${java.home}/../lib/tools.jar @
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception

H:\projects\forked\flatten-maven-plugin\src\it\projects\system-scope-dep-variabl
e>

**Comment by hohwille** [comment] 2015-12-01 07:38
As I said you reported a duplicate of #3.
If you run the IT from outside the build of flatten-maven-plugin your maven will pick 1.0.0-beta-5 what still has the bug #3 that is already fixed. Wait for the next release or run the entire build of the recent flatten-maven-plugin with ITs and see that it is now working.

**Comment by jameslittle** [comment] 2019-01-17 18:21
I am getting this issue on the latest version (1.1.0). Was the fix lost at some point? Or never covered this scenario?

```
[ERROR] Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.1.0:flatten (flatten) on project model.core: 1 problem was encountered while building the effective model for com.db.qdd:model.core:13.12.9.24-JL-SNAPSHOT
[ERROR] [ERROR] 'dependencies.dependency.systemPath' for com.db.ficstrat:fslib:jar must specify an absolute path but is ${fslib.path} @
```

where the dependency in question is: 

```
        <dependency>
            <groupId>com.db.ficstrat</groupId>
            <artifactId>fslib</artifactId>
            <version>${fslib.version}</version>
            <type>jar</type>
            <scope>system</scope>
            <systemPath>${fslib.path}</systemPath>
        </dependency>
```

**Comment by drivera-armedia** [comment] 2022-10-18 22:33
I fully understand that systemPath is on its way out. However, for some builds that we do for which the dependencies aren't available in a Maven-compatible repository, using systemPath is a viable option for the build.

The plugin version 1.3.0 is having problems with variable expansion on <systemPath> elements ... perhaps I missed a workaround, but for now it seems to still be broken.
